version: 2
jobs:
  lint:
    docker:
      - image: circleci/golang:1.17
    working_directory: /go/src/github.com/oxyno-zeta/kubernetes-tagger
    steps:
      - checkout
      - run: make lint
  build:
    docker:
      - image: circleci/golang:1.17
    working_directory: /go/src/github.com/oxyno-zeta/kubernetes-tagger
    steps:
      - checkout
      - run: make build
  test:
    docker:
      - image: circleci/golang:1.17
    working_directory: /go/src/github.com/oxyno-zeta/kubernetes-tagger
    steps:
      - checkout
      - run: make test
  release:
    docker:
      - image: circleci/golang:1.17
    working_directory: /go/src/github.com/oxyno-zeta/kubernetes-tagger
    steps:
      - checkout
      - setup_remote_docker
      - run: make release
workflows:
  version: 2
  project:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - test:
          requires:
            - build
      - release:
          requires:
            - build
